name: Generate ERD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: protobuf
        run: |
          curl -s -L -o thdcgrpc.tar.gz https://github.com/THD-C/Protocol/releases/latest/download/thdcgrpc.tar.gz && tar -xzf thdcgrpc.tar.gz && rm thdcgrpc.tar.gz && cp -r thdcgrpc/* . && rm -r thdcgrpc
  
      - name: Generate ERD
        run: |
          python ./DB_diagram_generator.py

      - name: Check if there are any changes
        id: diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and Push charts
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
  
          git add ./ERD.png
          git commit -m "update ERD"
          git push